import dash
import dash_bootstrap_components as dbc
from dash import html

dash.register_page(__name__)

layout = html.Div([

    # html.Div([
    #     #className="app-header",
    #     #children = [
    #     #    html.Div('Methodology', className="app-header--title")
    #     #]
    #     html.H1('References', style={'textAlign': 'left'}),
    #     html.P(['''Here are the datasets and information that have been used to create the dashboard.''',
        
    #     ], style={'textAlign': 'left'})], id='left-container'),

    html.Div([
        html.H1('References & further information', style={'textAlign': 'left'}),
        html.P('''This page contains links to similar tools and relevant articles and studies that consider similar questions to RQ1, RQ2 and RQ3. These references have influenced and provided inspiration for the Science and Ethics of Fair Shares (SEFS) dashboard and its design. The data sources that the SEFS dashboard draws on are also listed. '''),
        html.H2('Similar tools'),
        html.P('''Below are links to seven similar, dashboard-style tools and multi-country assessments. Many have a focus on fairness and equity, but seek to answer slightly different questions to those that the SEFS dashboard is focussed on.'''),
        dbc.Button("Climate Action Tracker",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://climateactiontracker.org/'),
        html.Br(),
        dbc.Button("Climate Equity Monitor",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://climateequitymonitor.in/'),
        html.Br(),
        dbc.Button("Climate Equity Reference Calculator",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://climateequityreference.org/'),
        html.Br(),
        dbc.Button("Eth Climate Calculator",
                   id="link-centered", 
                   className="ml-auto",
                   href='http://www.ccalc.ethz.ch/'),
        html.Br(),
        dbc.Button("Fair Mitigation Finance Explorer",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://data.ece.iiasa.ac.at/fairmitigation/'),
        html.Br(),
        dbc.Button("Greenhouse Development Rights",
                   id="link-centered", 
                   className="ml-auto",
                   href='http://gdrights.org/'),
        html.Br(),
        dbc.Button("Paris Equity Check",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://paris-equity-check.org/'),
        html.H2('Relevant articles and studies'),
        html.P('''The following references have influenced and provided inspiration for the SEFS dashboard.'''),
        dbc.Button('Callahan, C. W., & Mankin, J. S. (2022). National attribution of historical climate damages. Climatic Change, 172(3), Article 40. https://doi.org/10.1007/s10584-022-03387-y',
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.1007/s10584-022-03387-y'),
        html.Br(),
        html.Br(),
        dbc.Button("Kitzes, J. (2013). An introduction to Environmentally Extended Input-Output Analysis. Resources, 2, 489–503. https://doi.org/10.3390/resources2040502",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.3390/resources2040502'),
        html.Br(),
        html.Br(),
        dbc.Button('Page, E. A. (2012). Give it up for climate change: A defence of the beneficiary pays principle. International Theory, 4(2), 300–330. https://doi.org/10.1017/S175297191200005X',
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.1017/S175297191200005X'),
        html.Br(),
        html.Br(),
        dbc.Button("Pan, X., Wang, H., Lu, X., Zheng, X., Wang, L., & Chen, W. (2022). Implications of the consumption-based accounting for future national emissions budgets. Climate Policy, 1–13. https://doi.org/10.1080/14693062.2022.2067113",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.1080/14693062.2022.2067113'),
        html.Br(),
        html.Br(),
        dbc.Button("Rajamani, L., Jeffery, L., Höhne, N., Hans, F., Glass, A., Ganti, G., & Geiges, A. (2021). National ‘fair shares’ in reducing greenhouse gas emissions within the principled framework of international environmental law. Climate Policy, 21(8), 983–1004. https://doi.org/10.1080/14693062.2021.1970504",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.1080/14693062.2021.1970504'),

    ], style={'textAlign': 'left'}, id='left-container-refs'),
    html.Div([
        html.H1('Data', style={'color': '#FFFFFF'}),
        html.H2('Data sources'),
        html.P('''The SEFS dashboard draws on the following secondary data sources (linked below), which are publicly available.'''),
        html.H3('Data to answer RQ1'),
        dbc.Button("Callahan & Mankin (2022) study data - available on github",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://github.com/ccallahan45/CallahanMankin_NatlAttribution_2022'),
        html.Br(),
        # dbc.Button("UNFCCC Flexible Queries - Annex I Parties",
        #            id="link-centered", 
        #            className="ml-auto",
        #            href='https://di.unfccc.int/flex_annex1'),
        # html.Br(),
        # dbc.Button("UNFCCC Flexible Queries - Non-Annex I Parties",
        #            id="link-centered", 
        #            className="ml-auto",
        #            href='https://di.unfccc.int/flex_non_annex1'),
        # html.Br(),
        html.H3('Data to answer RQ2'),
        #html.H4('Ability to Pay'),
        dbc.Button("UNDP - HDI",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://hdr.undp.org/data-center/human-development-index#/indicies/HDI'),
        html.Br(),
        dbc.Button("World Bank Indicators - GDP",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://data.worldbank.org/indicator/NY.GDP.MKTP.CD'),
        html.Br(),
        dbc.Button("World Bank Indicators - GDP per capita",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://data.worldbank.org/indicator/NY.GDP.PCAP.CD'),
        html.Br(),
        dbc.Button("World Bank Indicators - GNI",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://data.worldbank.org/indicator/NY.GNP.MKTP.CD'),
        html.Br(),
        dbc.Button("World Bank Indicators - GNI per capita",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://data.worldbank.org/indicator/NY.GNP.PCAP.PP.CD'),
        html.Br(),
        #html.H4('Beneficiary Pays'),
        dbc.Button("World Bank Wealth Accounts - Total wealth and Total wealth per capita",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://databank.worldbank.org/source/wealth-accounts'),
        html.Br(),
        #html.H4('Polluter Pays'),
        dbc.Button("Callahan & Mankin (2022) study data - available on github",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://github.com/ccallahan45/CallahanMankin_NatlAttribution_2022'),
        html.Br(),
        dbc.Button("UNFCCC Flexible Queries - Annex I Parties",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://di.unfccc.int/flex_annex1'),
        html.Br(),
        # dbc.Button("UNFCCC Flexible Queries - Non-Annex I Parties",
        #            id="link-centered", 
        #            className="ml-auto",
        #            href='https://di.unfccc.int/flex_non_annex1'),
        html.H3('Data to answer RQ3'),
        #html.H4('Equal cumulative per capita emissions (ECPCE)'),
        dbc.Button("Pan et al. (2022), Supplementary Material: tcpo_a_2067113_sm9330.xlsx",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://doi.org/10.1080/14693062.2022.2067113'),
        html.Br(),
        #html.H4('Grandfathering'),
        dbc.Button("Callahan & Mankin (2022) study data - available on github",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://github.com/ccallahan45/CallahanMankin_NatlAttribution_2022'),
        html.Br(),
        dbc.Button("UNFCCC Flexible Queries - Annex I Parties",
                   id="link-centered", 
                   className="ml-auto",
                   href='https://di.unfccc.int/flex_annex1'),
        html.Br(),
        # dbc.Button("UNFCCC Flexible Queries - Non-Annex I Parties",
        #            id="link-centered", 
        #            className="ml-auto",
        #            href='https://di.unfccc.int/flex_non_annex1')
        #html.H4('Like Polluter Pays'),
    ], style={'textAlign': 'left'},  id='mid-container')
])